/* eslint-disable react/no-unescaped-entities */

import { useEffect, useState } from "react";
import Testimonial from "./Testimonial";
import Service from "./Service";

const servicesData = [
  {
    icon: "images/p3.jpg",
    title: "Arrow-up (Digital Learning Platform)",
    description:
      "• Developed a robust user authentication system, ensuring data security and secure platform access.                           • Engineered a dynamic personalized learning path feature, adapting to individual user progress and preferences while providing valuable insights.                                   • Incorporated a comprehensive feedback and rating system.      • Implemented cron jobs to send email notifications at selected intervals, increasing the number of returning visitors by 15%"
  },
  {
    icon: "images/p2.jpg",
    title: "Integration of SMS and Payment gateway",
    description:
      "• Integrated SMS (8x8, Unifonic, Link Mobility) and payment gateways (Pagalo, Myfatoorah) boosting transaction efficiency by 15%. • Spearhead the development of new gateways, targeting a 20% expansion in platform capabilities. • Conducting regular testing and quality assurance to identify and fix bugs to improve overall performance. • Utilize robust tech stacks (JavaScript, Node.js, Express, and MySQL) for seamless webhooks and essential module construction."
  },
  {
    icon: "images/p2.jpg",
    title: "URL Shortener",
    description:
      "Associated with Maulana Azad National Institute of Technology UrlShortener is a Web application which takes URL as an input and give it a short form of url which is generated by shortId package. You can find these package in npm library. Technologies used : NODEJS , EXPRESS.JS Framework , MONOGOOSE, EJS Template for rendering dynamic html."
  },
  {
    icon: "images/p3.jpg",
    title: "Home-tutor service",
    description:
      "Associated with Maulana Azad National Institute of Technology Home-Tutor Service is an online platform for Students who want to take Coaching from their home. This platform is beneficial for the students who don’t wants to spend more time on travelling or they living at far places from their residence."
  }
];

const About = () => {
  const [testimonials, setTestimonials] = useState([]);
  useEffect(() => {
    fetch("testimonials.json")
      .then(res => res.json())
      .then(data => {
        console.log(data);
        setTestimonials(data);
      });
  }, []);
  return (
    <article className="about  active" data-page="about">
      <header>
        <h2 className="h2 article-title">About me</h2>
      </header>

      <section className="about-text">
        <p>
          I am a results-driven software engineer with a proven track record of
          over 3 year's, specializing in innovative product development.
          Committed to delivering world-class solutions that redefine excellence
          within the industry.
        </p>

        <p>
          My expertise lies in backend development, where I bring a creative
          approach to building applications that prioritize functionality, user
          experience, and brand identity. My commitment is to ensure that your
          product not only works flawlessly but also resonates with your users,
          embodying the highest standards of quality and performance.
        </p>
      </section>

      {/* <!--
      - service
    --> */}

      <section className="service">
        <h3 className="h3 service-title">Projects i've done..</h3>

        <ul className="service-list">
          {servicesData.map((service, index) => (
            <Service
              key={index}
              icon={service.icon}
              title={service.title}
              description={service.description}
            />
          ))}
        </ul>
      </section>

      {/* <!--
      - testimonials
    --> */}

      <section className="testimonials">
        <h3 className="h3 testimonials-title">Certifications</h3>

        <ul className="testimonials-list has-scrollbar">
          {testimonials.map((testimonial, index) => (
            <Testimonial
              key={index}
              name={testimonial.name}
              avatar={testimonial.avatar}
              testimonial={testimonial.testimonial}
            />
          ))}
        </ul>
      </section>

      {/* <!--
      - clients
    --> */}
    </article>
  );
};

export default About;
